# Generated by Django 4.1.5 on 2023-01-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('overview', models.CharField(max_length=1000)),
                ('main_image', models.CharField(max_length=10000)),
                ('concept', models.TextField()),
                ('development', models.TextField()),
                ('project_github', models.URLField()),
            ],
        ),
    ]
