# Generated by Django 4.1.5 on 2023-01-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='project_fname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='project_lname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project_details',
            name='project_type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
